all : bruteForce.out dynamic.out backtrack.out huffman.out

.PHONY : all

bruteForce.out : bruteForce.c
	gcc bruteForce.c -o bruteForce.out

dynamic.out : dynamic.c
	gcc dynamic.c -o dynamic.out

backtrack.out : backtrack.c
	gcc backtrack.c -o backtrack.out

huffman.out : huffman.c
	gcc huffman.c -o huffman.out
